server:
  port: 8082

spring:
  application:
    name: pet-app

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: SYSTEM
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: PETAPP
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: petapp-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  elasticsearch:
    uris: http://localhost:9200

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/petapp-realm
          jwk-set-uri: http://localhost:8080/realms/petapp-realm/protocol/openid-connect/certs


petapp:
  soap:
    url: http://localhost:8089/soap/messages

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.kafka: INFO
    org.springframework.data.elasticsearch: INFO
