CREATE TABLE processing_messages (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message_id VARCHAR2(255) NOT NULL,
    thread_id VARCHAR2(255) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP WITH TIME ZONE
);
